name: run tests

on:
    push:
        branches: ["main"]

jobs:
    # Tests:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Use Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: 20
    #               cache: "npm"
    #         - run: npm ci
    #         - name: run tests
    #           env:
    #               AWSACCESS: ${{ secrets.AWSACCESS }}
    #               AWSREGION: ${{ secrets.AWSREGION }}
    #               AWSSECRET: ${{ secrets.AWSSECRET }}
    #               DATABASE_URL: ${{ secrets.DATABASE_URL }}
    #               DBNAME: ${{ secrets.DBNAME }}
    #               S3BUCKETNAME: ${{ secrets.S3BUCKETNAME }}
    #               SESSIONSECRET: ${{ secrets.SESSIONSECRET }}
    #               TESTPASSWORD: ${{ secrets.TESTPASSWORD }}
    #               TESTUSER: ${{ secrets.TESTUSER }}
    #               PORT: 0
    #           run: npm test
    Deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Connect to ec2 instance
              run: |
                  echo $SECRETSSHKEY > cotcRestfulApiKey.pem
                  ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
                  ssh -i cotcRestfulApiKey.pem $SSH_USER@$SSH_HOST
                  ls
              env:
                  SECRETSSHKEY: ${{ secrets.SECRETSSHKEY }}
                  SSH_USER: ${{ secrets.SSH_USER }}
                  SSH_HOST: ${{ secrets.SSH_HOST }}
